apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-env-cache
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-env-cache
  template:
    metadata:
      labels:
        app: dev-env-cache
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      initContainers:
      - name: nix-pre-populate
        image: nixos/nix:2.3.12
        imagePullPolicy: IfNotPresent
        command:
        - nix-shell
        - -p
        - rsync
        - --run
        args:
        - "rsync --info=progress2 -auvz /nix/ /to-populate-nix"
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: nix-dir
          mountPath: /to-populate-nix
      containers:
      - name: sshd
        image: nixos/nix:2.3.12
        imagePullPolicy: IfNotPresent
        command:
        - nix-shell
        - -p
        - openssh
        - --run
        args:
        - "bash /sshd_config_mnt/startup.sh"
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: coder-password
              key: coder-password
        ports:
        - name: ssh
          containerPort: 22
        volumeMounts:
        - name: nix-dir
          mountPath: /nix
        - name: sshd-config
          mountPath: /sshd_config_mnt
        - name: ssh-key
          mountPath: /ssh_key_mnt
        - name: ssh-host-key
          mountPath: /ssh_host_key_mnt
      volumes:
      - name: nix-dir
        emptyDir: {}
      - name: ssh-key
        secret:
          secretName: git-ssh-key
      - name: ssh-host-key
        secret:
          secretName: cache-ssh-host-key
      - name: sshd-config
        configMap:
          name: dev-env-cache-sshd-config
