kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dev-data-pvc
  namespace: dev
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: dev-data
