apiVersion: v1
kind: Secret
metadata:
  name: coder-password
  namespace: dev
stringData:
  coder-password: <path:kv/data/dev/coder-password#password>
---
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-key
  namespace: dev
stringData:
  id_rsa: <path:kv/data/dev/git-ssh-key#id_rsa>
  id_rsa.pub: <path:kv/data/dev/git-ssh-key#id_rsa.pub>
---
apiVersion: v1
kind: Secret
metadata:
  name: cache-ssh-host-key
  namespace: dev
stringData:
  ssh_host_rsa_key: <path:kv/data/dev/cache-ssh-host-key#ssh_host_rsa_key>
  ssh_host_rsa_key.pub: <path:kv/data/dev/cache-ssh-host-key#ssh_host_rsa_key.pub>
---
apiVersion: v1
kind: Secret
metadata:
  name: cache-signing-key
  namespace: dev
stringData:
  signing_key: <path:kv/data/dev/cache-signing-key#signing_key>
  signing_key.pub: <path:kv/data/dev/cache-signing-key#signing_key.pub>
