apiVersion: v1
kind: Secret
metadata:
  name: coder-password
  namespace: dev
stringData:
  coder-password: <path:kv/data/dev/coder-password#password>
---
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-key
  namespace: dev
stringData:
  id_rsa: <path:kv/data/dev/git-ssh-key#id_rsa>
  id_rsa.pub: <path:kv/data/dev/git-ssh-key#id_rsa.pub>
